chore: deactivate tinybird ci

diff --git a/.github/actions/tinybirdci/action.yaml b/.github/actions/tinybirdci/action.yaml
--- a/.github/actions/tinybirdci/action.yaml
+++ b/.github/actions/tinybirdci/action.yaml
@@ -166,98 +166,98 @@ runs:
         echo "TB_ENV_TOKEN=$ENV_TOKEN" >> $GITHUB_ENV
         echo "tb_branch_token=$ENV_TOKEN" >> $GITHUB_OUTPUT
 
-    - name: Deploy changes to the test Branch
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        source .tinyenv
-        DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
-        if [ ! -f "$DEPLOY_FILE" ]; then
-          echo "$DEPLOY_FILE not found, running default tb deploy command"
-          tb deploy ${CI_FLAGS}
-          tb release ls
-        fi
+    # - name: Deploy changes to the test Branch
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     source .tinyenv
+    #     DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+    #     if [ ! -f "$DEPLOY_FILE" ]; then
+    #       echo "$DEPLOY_FILE not found, running default tb deploy command"
+    #       tb deploy ${CI_FLAGS}
+    #       tb release ls
+    #     fi
 
-    - name: Custom deployment to the test Branch
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        source .tinyenv
-        DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
-        if [ -f "$DEPLOY_FILE" ]; then
-          echo "$DEPLOY_FILE found"
-          if ! [ -x "$DEPLOY_FILE" ]; then
-            echo "Error: You do not have permission to execute '$DEPLOY_FILE'. Run:"
-            echo "> chmod +x $DEPLOY_FILE"
-            echo "and commit your changes"
-            exit 1
-          else
-            $DEPLOY_FILE
-          fi
-        fi
+    # - name: Custom deployment to the test Branch
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     source .tinyenv
+    #     DEPLOY_FILE=./deploy/${VERSION}/deploy.sh
+    #     if [ -f "$DEPLOY_FILE" ]; then
+    #       echo "$DEPLOY_FILE found"
+    #       if ! [ -x "$DEPLOY_FILE" ]; then
+    #         echo "Error: You do not have permission to execute '$DEPLOY_FILE'. Run:"
+    #         echo "> chmod +x $DEPLOY_FILE"
+    #         echo "and commit your changes"
+    #         exit 1
+    #       else
+    #         $DEPLOY_FILE
+    #       fi
+    #     fi
 
-    - name: Post deploy
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        POSTDEPLOY_FILE=./deploy/${VERSION}/postdeploy.sh
-        if [ -f "$POSTDEPLOY_FILE" ]; then
-          if ! [ -x "$POSTDEPLOY_FILE" ]; then
-            echo "Error: You do not have permission to execute '$POSTDEPLOY_FILE'. Run:"
-            echo "> chmod +x $POSTDEPLOY_FILE"
-            echo "and commit your changes"
-            exit 1
-          else
-            $POSTDEPLOY_FILE
-          fi
-        fi
+    # - name: Post deploy
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     POSTDEPLOY_FILE=./deploy/${VERSION}/postdeploy.sh
+    #     if [ -f "$POSTDEPLOY_FILE" ]; then
+    #       if ! [ -x "$POSTDEPLOY_FILE" ]; then
+    #         echo "Error: You do not have permission to execute '$POSTDEPLOY_FILE'. Run:"
+    #         echo "> chmod +x $POSTDEPLOY_FILE"
+    #         echo "and commit your changes"
+    #         exit 1
+    #       else
+    #         $POSTDEPLOY_FILE
+    #       fi
+    #     fi
 
-    - name: Get regression labels
-      id: regression_labels
-      uses: alrocar/get-labels-action@v1.0.1
-      with:
-        github_token: ${{ inputs.GITHUB_TOKEN }}
-        label_key: regression
+    # - name: Get regression labels
+    #   id: regression_labels
+    #   uses: alrocar/get-labels-action@v1.0.1
+    #   with:
+    #     github_token: ${{ inputs.GITHUB_TOKEN }}
+    #     label_key: regression
 
-    - name: Run pipe regression tests
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        source .tinyenv
-        echo ${{ steps.regression_labels.outputs.labels }}
-        REGRESSION_LABELS=$(echo "${{ steps.regression_labels.outputs.labels }}" | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /^--/) print $i}' ORS=',' | sed 's/,$//')
-        echo "Regression labels: ${REGRESSION_LABELS}"
+    # - name: Run pipe regression tests
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     source .tinyenv
+    #     echo ${{ steps.regression_labels.outputs.labels }}
+    #     REGRESSION_LABELS=$(echo "${{ steps.regression_labels.outputs.labels }}" | awk -F, '{for (i=1; i<=NF; i++) if ($i ~ /^--/) print $i}' ORS=',' | sed 's/,$//')
+    #     echo "Regression labels: ${REGRESSION_LABELS}"
 
-        CONFIG_FILE=./tests/regression.yaml
-        BASE_CMD="tb branch regression-tests"
-        LABELS_CMD="$(echo ${REGRESSION_LABELS} | tr , ' ')"
-        if [ -f ${CONFIG_FILE} ]; then
-            echo "Config file '${CONFIG_FILE}' found, adding pull request labels as options"
-            ${BASE_CMD} -f ${CONFIG_FILE} --wait ${LABELS_CMD}
-        else
-            echo "Config file not found at '${CONFIG_FILE}', running with default values"
-            ${BASE_CMD} coverage --wait ${LABELS_CMD}
-        fi
+    #     CONFIG_FILE=./tests/regression.yaml
+    #     BASE_CMD="tb branch regression-tests"
+    #     LABELS_CMD="$(echo ${REGRESSION_LABELS} | tr , ' ')"
+    #     if [ -f ${CONFIG_FILE} ]; then
+    #         echo "Config file '${CONFIG_FILE}' found, adding pull request labels as options"
+    #         ${BASE_CMD} -f ${CONFIG_FILE} --wait ${LABELS_CMD}
+    #     else
+    #         echo "Config file not found at '${CONFIG_FILE}', running with default values"
+    #         ${BASE_CMD} coverage --wait ${LABELS_CMD}
+    #     fi
 
-    - name: Append fixtures
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        if [ -f ./scripts/append_fixtures.sh ]; then
-          echo "append_fixtures script found"
-          ./scripts/append_fixtures.sh
-        fi
+    # - name: Append fixtures
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     if [ -f ./scripts/append_fixtures.sh ]; then
+    #       echo "append_fixtures script found"
+    #       ./scripts/append_fixtures.sh
+    #     fi
 
-    - name: Run fixture tests
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        if [ -f ./scripts/exec_test.sh ]; then
-          ./scripts/exec_test.sh
-        fi
+    # - name: Run fixture tests
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     if [ -f ./scripts/exec_test.sh ]; then
+    #       ./scripts/exec_test.sh
+    #     fi
 
-    - name: Run data quality tests
-      shell: bash
-      working-directory: ${{ inputs.data_project_dir }}
-      run: |
-        tb test run -v -c 4
+    # - name: Run data quality tests
+    #   shell: bash
+    #   working-directory: ${{ inputs.data_project_dir }}
+    #   run: |
+    #     tb test run -v -c 4
