ci: introduce tinybird worflow

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,11 @@
+#!/usr/bin/env bash
+
+set -o errexit  # always exit on error
+set -o errtrace # trap errors in functions as well
+set -o pipefail # don't ignore exit codes when piping output
+set -o posix    # more strict failures in subshells
+
 echo "Running pre-commit hook"
+
 pnpm lint-staged
 pnpm test
